image: python:3.8

clone:
  depth: full

pipelines:
  default:
    - step:
          name: Build
          script:
            - pip install -r backend/requirements.txt
            - git archive --format=tar.gz develop -o chaty.tar.gz
          artifacts:
            - chaty.tar.gz
    - step:
        name: Deploy to production
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:1.2.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: 'chaty.tar.gz'